### ISSUE TITLE
Fix page doc/examples/ 

### ISSUE THREAD

**Issue by jonnyfoka** [BNN-UPC/ignnition#115]
When trying to access the library with examples of GNNs already implemented, the page does not seem to exist:

https://ignnition.org/doc/examples/

**Comment by MiquelFerriol** [comment]
Dear @jonnyfoka,

Thank you very much for pointing this out. We modified the way we generate the /docs/ and looks like the URLs have changed.
The problem should be fixed now.

Thanks,
Miquel
