### ISSUE TITLE
GPU and cuda support

### ISSUE THREAD

**Issue by aaronfderybel** [BNN-UPC/ignnition#116]
Hello,

Is there currently a way to use GPU instead of CPU ?
I started training GNN using the following example GIT project: https://github.com/BNN-UPC/GNN-NIDS
using the function `model.train_and_validate()`  and receive following output:
![image](https://user-images.githubusercontent.com/43145159/163582646-37f30a46-4d27-40e3-88ae-8f8d62080084.png)

**Comment by aaronfderybel** [comment]
closing this issue. IGNNITION uses tensorflow in the background. My device was not properly set up for tensorflow, working now

**Comment by MiquelFerriol** [comment]
As @AaronDeRybelHowest pointed out, in order to use the GPU, it is needed to set up [CUDA for Tensorflow](https://www.tensorflow.org/install/gpu?hl=es-419).

Closing this issue.
