### ISSUE TITLE
Hyperparameter optimization

### ISSUE THREAD

**Issue by ognjenkundacina** [BNN-UPC/ignnition#124]
Hello,

I am currently working with ignnition models, and I am interested in performing hyperparameter optimization for them. I was wondering if it is possible to do so and if there are any examples available that could help me get started.

Thank you for your time, and any help you can provide would be greatly appreciated!

Ognjen

**Comment by MiquelFerriol** [comment]
Dear @ognjenkundacina ,
I am glad to hear from you again. Thanks for your interest shown in IGNNITION!

Currently, IGNNITION does not natively support Hyperparameter Optimisation (although we have a development branch trying to implement it). However, you could always generate a script that changes the desired hyperparameters found in the YAML files (```model_description.yaml```, ```global_variables.yaml```, and ```train_options.yaml```), trains the model and evaluate its performance for each one of the modified YAML files.

Then, you could easily compare them using Tensorboard and select the one with the best performance.

Hope it helps,
Best regards,
Miquel

**Comment by ognjenkundacina** [comment]
Dear Miquel,

Thank you for the advice!

Bests,

Ognjen
